name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t payvault-api .

    - name: Run Tests
      run: dotnet test

    - name: Push to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        docker tag payvault-api ${{ secrets.DOCKER_USER }}/payvault-api
        docker push ${{ secrets.DOCKER_USER }}/payvault-api